### PR TITLE
adding story folders for Bootstrap and Editable cells

### PR DESCRIPTION
**Pull request by headwinds**
I saw a request in the issues to test various versions of Bootstrap as well as an Editable cells so I setup the stories to add individual story folders for these features.

I'm also interested in your thoughts around providing Editable cells that dispatch events through sematable so the new Editable Cell story could be a good place to try out and discuss some approaches.

### CODE REVIEW

**Comment by amir-hadzic** [comment]
Hello,

Thanks for the additional examples, this will be very useful.

I've tried running this locally, and I think we will not be able to test different bootstrap versions like this. Loading bootstrap css in this way loads both 4.0.0 and 3.3.7 bootstrap css at the same time. The old import for bootstrap from `node_modules` is left as well, so we have three different versions of bootstrap loaded at the same time.

I would suggest removing the old import for bootstrap, and removing the individual stories for different versions of bootstrap. Instead, we could specify which bootstrap version to use when running storybook, and then all stories would use the specified bootstrap version.

I've poked around and it should be easy to adjust this if you are interested in making the changes.

Making the following changes in `.storybook/config.js`, and `.storybook/webpack.config.js` would allow the user to specify the bootstrap version when running storybook like this:

```
BOOTSTRAP_VERSION=3.3.7 npm run storybook
```

We would use boostrap 4 by default.

```diff
diff --git a/.storybook/config.js b/.storybook/config.js
index 65c4816..92b22e5 100644
--- a/.storybook/config.js
+++ b/.storybook/config.js
@@ -1,5 +1,5 @@
 import { configure } from '@kadira/storybook';
-import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
+import 'bootstrapCss';
 import '../node_modules/react-select/dist/react-select.min.css';
 
 function loadStories() {
diff --git a/.storybook/webpack.config.js b/.storybook/webpack.config.js
index 379362c..72de15b 100644
--- a/.storybook/webpack.config.js
+++ b/.storybook/webpack.config.js
@@ -1,13 +1,23 @@
+const path = require('path');
 const genDefaultConfig = require('@kadira/storybook/dist/server/config/defaults/webpack.config.js');
 const webpack = require('webpack');
 
+const bootstrapVersion = process.env.BOOTSTRAP_VERSION || '4.0.0';
 
 module.exports = function(config, env) {
   const defaultConfig = genDefaultConfig(config, env);
   const withOldPlugin = Object.assign({}, defaultConfig, {
     plugins: defaultConfig.plugins.concat([
       new webpack.OldWatchingPlugin(),
-    ])
+    ]),
+    resolve: Object.assign({}, defaultConfig.resolve, {
+      alias: Object.assign({}, defaultConfig.resolve.alias, {
+        bootstrapCss: path.join(
+          __dirname,
+          '../stories/bootstrap/v' + bootstrapVersion + '/css/bootstrap.min.css'
+        ),
+      }),
+    }),
   })
   return withOldPlugin;
 };
```

Let me know if you want to make these changes, otherwise I can merge & adjust. Thanks again for your contribution!

**Comment by amir-hadzic** [comment]
> I'm also interested in your thoughts around providing Editable cells that dispatch events through sematable so the new Editable Cell story could be a good place to try out and discuss some approaches.

I think adding an example like you did is the right way to go. Maybe we can add a guide that explains to users how they can create their own EditableCell.

I'm not sure if EditableCell component would be complicated enough that we would need to provide it out-of-box with sematable. I also feel like this is something that users would want to heavily customize so I'm not sure what "common" functionality we could provide. Did you have any ideas on how this would work?

**Comment by headwinds** [comment]
Yes, I'll make those changes to Bootstrap - I was hoping you would suggest them! I should have mentioned that I realized it wasn't working. Configuring it is a fine approach and I'll add some instructional copy in the story about switching versions.  

I think you've done enough to provide the hook for a custom cell and then allowing others to create their own. For instance, in my case, I need an editable cell that can also provide autosuggest. All I need is an example to see where I can add my custom cell and how it might dispatch actions so that the new state is saved.

If a cell changes, can I dispatch a Sematable action that has the value of the cell and it's row data object to map it back to the table's data? Is there already an action like rowChanged( rowData ) and a type like ROW_CHANGE. 

OR

I could approach the story by adding my own action, type, and reducer. Probably the former makes more sense to have only 1 Sematable reducer that could talk to a custom cell.

**Comment by amir-hadzic** [comment]
Hello,

> I could approach the story by adding my own action, type, and reducer. Probably the former makes more sense to have only 1 Sematable reducer that could talk to a custom cell.

I think this is probably the better approach (to have your own action and reducer). The app that uses sematable will probably already keep the data in state somewhere, and changing the cells should probably change this data in the app state, not in sematable state.

For example, imagine you have a table with a list of users (from app state), and an editable cell for the "email" field. Changing the value should probably dispatch an action that will update that user in app state through the "users" reducer, and also dispatch an action to update the user data on backend. Since the data is updated in app state, sematable will also display the updated email value.

**Comment by headwinds** [comment]
Ok I've made those recommended changes and pushed them. I removed the Bootstrap story since Default is already bootstrap. It might be a nice to have a vanilla table but let's leave that story for another rainy day.

**Comment by amir-hadzic** [comment]
Thanks @headwinds, sorry it took me a while to get around merging this.

**Comment by headwinds** [comment]
no worries - I shouldn't have left it with any merge conflicts - thanks @amir-hadzic !

**Pull request merged**
