### PR TITLE
Custom sort icons and pagination classes

### PR DESCRIPTION
**Pull request by godd9170**
Hi There,

Found this repo via a blog post on a pursuit to make jquery DataTables Frankenstein into a React-Redux project. It really peaked my interest and I've since been tinkering with Sematable for about a day now.

This PR introduces the option for custom sorting icons, as well as extends the option to set paginationContainerClassName and paginationClassName. Seemed like a natural option given both pageSize and filter had them.

Let me know what you think.

### CODE REVIEW

**Comment by godd9170** [comment]
Hey @otisg ,

Take a look and let me know if this PR abides with what you're trying to achieve with Sematable. I've added a few `config` options that are outlined in the `README`. I'm pretty happy with the added functionality in my own project and it certainly introduces no breaking changes.

-H

**Comment by otisg** [comment]
@amir-hadzic will be able to look at this (but in a few weeks, after returning from vacation)

**Comment by godd9170** [comment]
Awesome, no rush! Really thankful for the repo thus far. Happy Vacation @amir-hadzic

**Comment by mbonaci** [comment]
Thanks for that effort, @godd9170.
The project was deprecated on Mar 7, 2022.
Closing the PR.

**Pull request closed without merging**
