### PR TITLE
PageSize - Remove totalSize

### PR DESCRIPTION
**Pull request by gor181**
#35

### CODE REVIEW

**Comment by amir-hadzic** [comment]
@gor181: From the comments in #35, I assume that this is not done yet ?

**Comment by gor181** [comment]
@amir-hadzic @otisg 

This is how it looks at the moment.

We can add `Showing n of n results` however I'm unsure how that information is handled @amir-hadzic?  Do we rely on all rows being loaded into the table in order to display pagination or there is an option to accept some sort of properties which would denote `currentPage` and `maxPages` so once a page in pagination component has been clicked results would be loaded async?

image

**Comment by otisg** [comment]
This doesn't look quite right...

If there is > 1 page worth of rows, and we are showing 5 rows per page, then bottom-right should say "Showing 5 of N"

If there is < 1 page worth of rows then the bottom should not say "Showing 5 of N"...
... but note that if the number of rows being shown per page is not very small and thus not quick and easy to count (which could mean anything above 5), we do want to show is the total count of rows.

**Comment by mbonaci** [comment]
Thanks for that attempt, @gor181.
The project was deprecated on Mar 7, 2022.
Closing the PR.

**Pull request closed without merging**
